# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-05 07:53
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='b_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='business/'),
        ),
        migrations.AlterField(
            model_name='hood',
            name='hood_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='hoods/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='profiles/'),
        ),
    ]
